name: Continuous CI/CD

on:
  push:
    branches: [ "vue-port", "feature/*" ]
  pull_request:
    branches: [ "vue-port" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build the application
        run: yarn build

#      - name: Deploy to GH pages
#        run: yarn deploy

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "mail@christiangebauer.de"
          git config --global user.name "Christian Gebauer"
          npx gh-pages -d dist --dotfiles --nojekyll -u "Christian Gebauer <mail@christiangebauer.de>" -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
